# Generated by Django 2.1.2 on 2018-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='厂商')),
                ('car_type', models.CharField(max_length=50, verbose_name='型号')),
                ('car_color', models.CharField(max_length=40, verbose_name='颜色')),
                ('car_weight', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
            },
        ),
    ]
