# Generated by Django 2.1.2 on 2018-11-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_weight',
            new_name='car_count',
        ),
    ]
