# Generated by Django 2.1.2 on 2018-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo01', '0002_auto_20181112_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(max_length=50, verbose_name='类型'),
        ),
    ]
