# Generated by Django 2.1.2 on 2018-12-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo03', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
