# Generated by Django 2.1.2 on 2018-12-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='bug_no',
            new_name='bug_code',
        ),
    ]
