# Generated by Django 2.1.2 on 2018-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo02', '0002_auto_20181210_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='bug_priority',
            field=models.IntegerField(default=1, verbose_name='缺陷优先级'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='bug_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='缺陷编号'),
        ),
    ]
