# Generated by Django 2.1.2 on 2018-12-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo02', '0003_auto_20181211_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='bug_desc',
            field=models.CharField(max_length=500, null=True, verbose_name='缺陷描述'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='bug_priority',
            field=models.IntegerField(default=1, null=True, verbose_name='缺陷优先级'),
        ),
    ]
